### ISSUE TITLE
Cant find new options

### ISSUE THREAD

**Issue by tal0nmallorca** [e00E/obs-amf#8]
New Auto LTR encoder mode ? I dont know what's this and where to find the option.

FFmpeg updated to version 4.3.2? Can we insert options with a command line? What options I can input?

New encoder usage presets? I only see the always "Quality, balanced and speed"

However, very thanks for awesome job.

Thank you

**Comment by e00E** [comment]
This project has no relation to ffmpeg but yes there is new AMF release to which it hasn't bee updated yet.

**Comment by tal0nmallorca** [comment]
Oh really! New release? When we can take it!!?

Thank you a lot

**Comment by e00E** [comment]
AMF is the library made my AMD that this plugin uses. AMF had a new releases with new options that you are talking about I think. This plugin has not been updated to the newest AMF release so you cannot use those options yet.

**Comment by tal0nmallorca** [comment]
So, this plugin not uses new Auto LTR encoder mode?

**Comment by e00E** [comment]
Amd mentioned this auto ltr encoder mode in their release mode. It does not show up in the documentation for the components this plugin is using so it doesn't seem relevant. The usage preset doesn't show up in the OBS settings because this plugin hard codes them as I see no reason to expose this to the user at the moment.
